#!/usr/bin/env python

import os
from glob import glob

all_focused = os.environ.get("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS", "").strip()
all_focused = all_focused.split('\n')
print('all_focused:', all_focused)

complete_list = []
for i, focus in enumerate(all_focused):
    print(f'folder {i + 1}/{len(all_focused)}:', focus)

    print('Running listdir...')
    l = []
    for ext in ('jpg', 'JPG', 'jpeg', 'JPEG', 'png', 'PNG'):
        l_part = list(glob(os.path.join(focus, '**', f'*.{ext}'), recursive=True))
        print(f'found {len(l_part)} .{ext} files')
        l.extend(l_part)

    print('Converting to absolute paths...')
    l = [os.path.join(focus, name.strip()) for name in l]

    complete_list.extend(l)

complete_list.sort()

all_focused_bns = [os.path.basename(focus) for focus in all_focused]
out_file_path = os.path.join(os.path.dirname(focus), 
                             '_'.join(all_focused_bns) + "_file_list.txt")
print('Writing to the file...')
with open(out_file_path, 'w') as fout:
    fout.write('\n'.join(complete_list))

print('Done, see', out_file_path)
